# Generated by Django 2.2.15 on 2021-05-25 15:48

from django.db import migrations, models
import localflavor.cl.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170919_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(default='Rut is missing', max_length=20, unique=True, validators=[localflavor.cl.forms.CLRutField.clean], verbose_name='rut'),
        ),
    ]
