# Generated by Django 2.2.15 on 2021-05-25 16:08

from django.db import migrations

def modify_rut_admin_user(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model('users', 'User')

    user_admin = User.objects.get(email='alex.smith@example.com')
    user_admin.rut = '76.224.628-7'
    user_admin.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rut'),
    ]

    operations = [
        migrations.RunPython(modify_rut_admin_user),
    ]
