# Generated by Django 2.2.15 on 2021-05-25 21:07

from django.db import migrations, models
import localflavor.cl.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_rut_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=20, unique=True, validators=[localflavor.cl.forms.CLRutField.clean], verbose_name='rut'),
        ),
    ]
