# Generated by Django 2.2.15 on 2021-05-25 20:58

import base.mixins
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True, verbose_name='updated at')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('check_in_time', models.TimeField(default=datetime.time(9, 0), verbose_name='check in time')),
                ('check_out_time', models.TimeField(default=datetime.time(18, 0), verbose_name='check out time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
    ]
